Implement Matrix3 class
apojomovsky/cppl1_q12020 pull request #2
Opened 2020-09-28 00:30 UTC by apojomovsky

This PR includes:

- Initial implementation of the matrix3 class required to make all the tests from matrix3_TEST suite to pass.

2020-09-30 21:09 UTC, francocipollone approved these changes
Excellent job!. I've just commented on a few things because something I had to say :D.

I also leave some recommendations about the docstrings. Not all the languages are commented the same way so I leave a couple of examples. But in essence, it is a good practice to have in every function:
 - A brief description
 - parameters involved.
 - return of the function
 - throws if any.

2020-09-30 21:09 UTC, francocipollone commented on course/include/isometry/matrix3.hpp
> +  const Vector3 row(int index) const;
There is no need to return a `const Vector3`

Keep in mind that if you return `const Vector3` then you won't be able to do the following:
```c++
// being `matrix` a Matrix3 instance.
Vector3 v = matrix.row(2);
v =* 2; 
```
Because only a `const` variable could allocate the return of the method `const Vector3 row(int) const`

2020-09-30 21:09 UTC, francocipollone commented on course/src/matrix3.cpp
> +  return aux;
nit: You can just simply do:

```suggestion
  return {a_.dot(vector), b_.dot(vector), c_.dot(vector)};
```

2020-09-30 21:09 UTC, francocipollone commented on course/include/isometry/matrix3.hpp
> +  /// \brief Constructor.
Just a nit/suggestion/recommendation:
```c++
  /// Constructs a 3-dimensional matrix from a list of doubles.
  /// @param a1 First row, first column element.
  /// @param a2 First row, second column element.
  /// @param a3 First row, third column element.
  /// @param b1 Second row, first column element.
  /// @param b2 Second row, second column element.
  /// @param b3 Second row, third column element.
  /// @param c1 Third row, first column element.
  /// @param c2 Third row, second column element.
  /// @param c3 Third row, third column element.
```
Of course here is trivial but it is just for keeping the habit.

2020-09-30 21:09 UTC, francocipollone commented on course/include/isometry/matrix3.hpp
> +  /// \brief Returns a reference to a row.
Just a nit/suggestion/recommendation:
```c++
  /// Returns a reference to a row.
  /// @param index Row number.
  /// @returns A Vector3.
  ///
  /// @throw std::out_of_range When `index` is less than 0 or greater than 2.
```

2020-09-30 21:10 UTC, francocipollone commented
@glpuga You can review if you want, I just left minor comments.

2020-10-02 15:07 UTC, glpuga requested changes
Good work! Some comments below.

2020-10-02 15:07 UTC, glpuga commented on course/include/isometry/matrix3.hpp
> +  /// \return An rval copy of the requested field.
What does this return? rows or columns?

2020-10-02 15:07 UTC, glpuga commented on course/include/isometry/matrix3.hpp
> +  Matrix3& operator*=(double scalar);
nit: argument can be const.

2020-10-02 15:07 UTC, glpuga commented on course/include/isometry/matrix3.hpp
> +  Matrix3& operator/=(double scalar);
nit: argument can be const.

2020-10-02 15:07 UTC, glpuga commented on course/include/isometry/matrix3.hpp
> +  Matrix3 operator*(double scalar) const;
nit: argument can be const.

2020-10-02 15:07 UTC, glpuga commented on course/include/isometry/matrix3.hpp
> +  const Vector3 row(int index) const;
Don't use `const` on the return value unless it's a read only reference. You prevent the compiler from being able to move from the temporary object.

See https://godbolt.org/z/nP3Y63 .

2020-10-02 15:07 UTC, glpuga commented on course/include/isometry/matrix3.hpp
> +  const Vector3 row(int index) const;
nit: Argument can be const.

2020-10-02 15:07 UTC, glpuga commented on course/include/isometry/matrix3.hpp
> +  Vector3 col(int index) const;
nit: argument can be const.

2020-10-02 15:07 UTC, glpuga commented on course/include/isometry/matrix3.hpp
> +Matrix3 operator*(double scalar, const Matrix3& matrix);
nit: `scalar` can be const.

2020-10-02 15:07 UTC, glpuga commented on course/include/isometry/matrix3.hpp
> +  Vector3 b_;
Are these rows? columns? it would be better if the name gave a hint about that.

2020-10-02 15:07 UTC, glpuga commented on course/test/src/matrix3_TEST.cpp
> +  EXPECT_NEAR(m3.det(), 0., kTolerance);
Why is this change needed?

2020-10-04 16:09 UTC, apojomovsky commented on course/include/isometry/matrix3.hpp
> +  /// \return An rval copy of the requested field.
rows, I just specified it in the docstring.

2020-10-04 16:20 UTC, apojomovsky commented on course/include/isometry/matrix3.hpp
> +  const Vector3 row(int index) const;
Thanks for the excellent example, Gera!

2020-10-04 16:49 UTC, apojomovsky commented on course/test/src/matrix3_TEST.cpp
> +  EXPECT_NEAR(m3.det(), 0., kTolerance);
Hm, it was a typo. I just restored it.

2020-10-04 16:49 UTC, apojomovsky commented
Thanks for the review @francocipollone and @glpuga . Your comments have been addressed. PTAL

2020-10-04 23:22 UTC, glpuga approved these changes
LGTM!

2020-10-04 23:22 UTC, glpuga commented
Please merge and move to the next stage!

2020-10-05 12:25 UTC, merged